title: American Handel Society
email: reginafcompton@gmail.com
description: >
  Website for the American Handel Society
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  americanhandelsociety

# Build settings
sass:
  style: :compressed
include: ['_pages']
exclude: ['vendor']
kramdown:
  input: GFM


